name: pg1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  # # Firebase Core - Required to initialize Firebase services
  # firebase_core: ^2.24.2
  # # Cloud Firestore - Store session results in database
  # cloud_firestore: ^4.15.8
  # # Bloc - State management for card flow and session state
  flutter_bloc: ^9.1.1
  # Go Router - Handle navigation between onboarding, cards, and results
  go_router: ^17.0.0
  # UUID - Generate unique session IDs
  uuid: ^4.3.3
  # Equatable - Simplify equality comparisons in models and Bloc states
  equatable: ^2.0.5
  flutter_svg: ^2.2.3
  
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/json/cards-json.json
    - assets/json/mappings-json.json
    - assets/json/centroids-json.json
    - assets/json/narratives-json.json
    - assets/json/pattern-insights-json.json
    - assets/png/


  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/inter/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/font/inter/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/font/inter/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/font/inter/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/font/inter/Inter_18pt-Bold.ttf
          weight: 700
    
    - family: SFProText
      fonts:
        - asset: assets/font/text/SF-Pro-Text-Ultralight.otf
          weight: 100
        - asset: assets/font/text/SF-Pro-Text-Thin.otf
          weight: 200
        - asset: assets/font/text/SF-Pro-Text-Light.otf
          weight: 300
        - asset: assets/font/text/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/font/text/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/font/text/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: assets/font/text/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/font/text/SF-Pro-Text-Heavy.otf
          weight: 800
        - asset: assets/font/text/SF-Pro-Text-Black.otf
          weight: 900
